// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function Chat(arg1:string,arg2:string):Promise<string>;

export function CheckOllama():Promise<boolean>;

export function ClearChatHistory(arg1:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetChatHistory(arg1:string):Promise<Array<main.ChatMessage>>;

export function GetConfig():Promise<config.Config>;

export function GetKakaoConfig():Promise<main.KakaoConfigJS>;

export function GetKakaoStatus():Promise<main.KakaoStatus>;

export function GetOllamaModels():Promise<Array<string>>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetToolList():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function ParseHWP(arg1:string,arg2:boolean):Promise<main.HWPParseResult>;

export function PullOllamaModel(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetOllamaModel(arg1:string):Promise<void>;

export function SimpleChat(arg1:string,arg2:string):Promise<string>;

export function StartKakaoServer():Promise<void>;

export function StartOllama():Promise<void>;

export function StopKakaoServer():Promise<void>;

export function UpdateKakaoConfig(arg1:main.KakaoConfigJS):Promise<void>;
